apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-cicd

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-cicd-serviceaccount
  namespace: jenkins-cicd

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins-cicd-serviceaccount
  namespace: jenkins-cicd
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
  